#!/bin/bash

# Check if pyinstaller is installed
if ! command -v pyinstaller &> /dev/null; then
    echo "PyInstaller not found. Installing..."
    pip install pyinstaller
fi

# Define the Python scripts and their output names
SCRIPTS=("filelabeler.py" "addresslabeler.py")
OUTPUT_NAMES=("filelabeler" "labeler")
DESTINATION_DIR="$HOME/.local/bin"

# Create destination directory if it doesn't exist
mkdir -p "$DESTINATION_DIR"

# Build each application
for i in "${!SCRIPTS[@]}"; do
    script=${SCRIPTS[$i]}
    output_name=${OUTPUT_NAMES[$i]}

    echo "Building $script with PyInstaller..."
    pyinstaller --onefile --name "$output_name" "$script"

    # Check if the build was successful
    if [ ! -f "dist/$output_name" ]; then
        echo "Build for $script failed. Skipping."
        continue
    fi

    echo "Copying $output_name to $DESTINATION_DIR..."
    cp "dist/$output_name" "$DESTINATION_DIR/"

    # Make sure the file is executable
    chmod +x "$DESTINATION_DIR/$output_name"
done

# Cleanup build files generated by PyInstaller
echo "Cleaning up temporary build files..."
rm -rf build dist __pycache__
rm -f *.spec

echo "Build and installation complete. Executables are located in $DESTINATION_DIR."
