#!/bin/bash

# Check if pyinstaller is installed
if ! command -v pyinstaller &> /dev/null; then
    echo "PyInstaller not found. Installing..."
    pip install pyinstaller
fi

# Define the Python script and output locations
SCRIPT_NAME="filelabeler.py"
OUTPUT_NAME="filelabeler"
DESTINATION_DIR="$HOME/.local/bin"

# Run PyInstaller to build the standalone executable
echo "Building executable with PyInstaller..."
pyinstaller --onefile --name "$OUTPUT_NAME" "$SCRIPT_NAME"

# Check if the build was successful
if [ ! -f "dist/$OUTPUT_NAME" ]; then
    echo "Build failed. Exiting."
    exit 1
fi

# Create destination directory if it doesn't exist
mkdir -p "$DESTINATION_DIR"

# Copy the executable to ~/.local/bin
echo "Copying executable to $DESTINATION_DIR..."
cp "dist/$OUTPUT_NAME" "$DESTINATION_DIR/"

# Make sure the file is executable
chmod +x "$DESTINATION_DIR/$OUTPUT_NAME"

# Cleanup build files generated by PyInstaller
echo "Cleaning up temporary build files..."
rm -rf build dist __pycache__
rm "$OUTPUT_NAME.spec"

echo "Build and installation complete. You can now run '$OUTPUT_NAME' from the command line."
